---
- name: Run services
  become: true
  
  vars:
    rhel_services:
      - firewalld
      - httpd
      - auditd
      - nginx
      - sshd
      - mariadb


    debian_services:
      - ufw
      - apache2
      - auditd
      - nginx
      - ssh
      - mariadb

    os_families:
      - RedHat
      - Debian

  block:
    - name: Run services
      service: 
        enabled: true    
        state: reloaded    
        name: "{{ item.0 if ansible_os_family == 'RedHat' else item.1 }}"
      loop: "{{ rhel_services | zip(debian_services) | list }}"
      notify: Reload 
