---
- name: Install node exporter
  become: true

  vars:
    packages:
      - name: node
        url: https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz
        archive: /tmp/node
        extract: /opt

  block:

    - name: Download gz
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.archive }}"
        mode: "0644"
      loop: "{{ packages }}"
     
    - name: Extract 
      ansible.builtin.unarchive:
        src: "{{ item.archive }}"
        remote_src: yes
        dest: "{{ item.extract }}"
      loop: "{{ packages }}"

    - name: delete gz
      ansible.builtin.file:
        path: "{{ item.archive }}"
        state: absent
      loop: "{{ packages }}"
        
- name: Run Node Exporter
  ansible.builtin.shell:
    cmd: "/opt/node_exporter-1.11.1.linux-amd64/node_exporter > /tmp/node_exporter.log 2>&1 &"
