- name: Configure Users
  become: true

  block:
    - name: create admin groups
      group:
        name: admin
        state: present

    - name: create admin
      user:
        name: admin
        append: true
        group: admin
        groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
        password_expire_min: 1
        password_expire_max: 90
        password_expire_warn: 14
        home: /home/admin
        shell: /bin/bash



