---
- name: Manage Static MOTD
  hosts: all
  become: true
  tasks:
    - name: Copy static MOTD banner to target hosts
      ansible.builtin.copy:
        src: files/motd
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
