---
- name: Install Packages
  become: true

  vars:
    rhel_packages:
      - firewalld
      - httpd
      - audit

    debian_packages:
      - ufw
      - apache2
      - auditd

    universal_packages:
      - nginx
      - openssh-server
      - mariadb-server
      - wget

  block:

    - name: Update Debian package cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install RedHat packages
      ansible.builtin.dnf:
        name: "{{ rhel_packages + universal_packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Debian packages
      ansible.builtin.apt:
        name: "{{ debian_packages + universal_packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Update Debian Packages
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
 
        
