    regexps:
      - "^#?PermitRootLogin[[:space:]]*"
      - "^#?PasswordAuthentication[[:space:]]*"
      - "^#?PermitEmptyPasswords[[:space:]]*"
    
    lines:
      - PermitRootLogin no
      - PasswordAuthentication no
      - PermitEmptyPasswords no